bank_dict = {
    "Central Bank of UAE": "CBAU",
    "The Royal Bank Of Scotland PLC": "ABNA",
    "Abu Dhabi Commercial Bank": "ADCB",
    "Al Ahli Bank Of Kuwait K.S.C.": "ABKK",
    "Rafidain Bank": "RAFB",
    "Arab African International Bank": "ARAI",
    "Al Masraf": "ABIN",
    "Arab Bank": "ARAB",
    "Bank Melli Iran": "MELI",
    "Bank of Baroda": "BARB",
    "Bank of Sharjah": "SHAR",
    "Bank Saderat Iran": "BSIR",
    "Blom Bank France": "BLOM",
    "Banque Misr": "BCAI",
    "Credit Agricole Corporate and Investment Bank": "BSUI",
    "Al Khaliji France S.A.": "LICO",
    "BNP Paribas": "BNPA",
    "Barclays Bank": "BARC",
    "HSBC Bank Middle East": "BBME",
    "Citibank NA": "CITI",
    "Commercial Bank International PS": "CLBI",
    "Commercial Bank of Dubai": "CBDU",
    "Dubai Islamic Bank": "DUIB",
    "El Nilein Bank": "NILB",
    "EmiratesNBD Bank PJSC": "EBIL",
    "First Gulf Bank": "FGBM",
    "Habib Bank Limited": "HABB",
    "Habib Bank AG Zurich": "HBZU",
    "Investbank PSC": "IBTF",
    "Janata Bank": "JANB",
    "Mashreqbank": "BOML",
    "Emirates Islamic Bank PJSC": "MEBL",
    "National Bank of Abu Dhabi": "NBAD",
    "National Bank Of Bahrain": "NBOB",
    "National Bank Of Fujairah": "NBFU",
    "National Bank of Oman": "NBOM",
    "RAK Bank": "NRAK",
    "Sharjah Islamic Bank": "NBSH",
    "National Bank Of Umm Al Qaiwain": "UMMQ",
    "Industrial and Commercial Bank of China": "ICBK",
    "Standard Chartered Bank": "SCBL",
    "Union National Bank": "UNBE",
    "United Arab Bank": "UARB",
    "United Bank Ltd.": "UNIL",
    "Emirates Investment Bank": "AEIN",
    "Deutsche Bank": "DEUT",
    "Abu Dhabi Islamic Bank": "ABDI",
    "Dubai Bank": "DBXP",
    "Noor Bank": "NISL",
    "Al Hilal Bank": "HLAL",
    "Doha Bank": "DOHB",
    "SAMBA Financial Group": "SAMB",
    "National Bank Of Kuwait": "NBOK",
    "Ajman Bank": "AJMN",
    "Finance House": "FHOU",
    "The Bank of Tokyo-Mitsubishi UFJ, Ltd": "BOTK",
    "KEB HANA Bank": "KOEX",
    "Bank Of China": "BKCH",
    "MCB Bank Limited": "MUCB",
    "Gulf International Bank B.S.C.": "GULF",
    "EMIRATES DEVELOPMENT BANK": "EMDV"
}
